import Head from 'next/head'

import { navItems } from '../lib/navbar'
import { socialItems } from '../lib/social'

import Header from '../components/shared/Navbar'
import Footer from '../components/shared/Footer'
import TopSection from '../components/home/TopSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header items={navItems} />
      <TopSection />
      <Footer items={navItems} socialItems={socialItems} />
    </>
  )
}
