import Head from 'next/head'

import ColorModeButton from '../components/buttons/ColorModeButton'
import Hello from '../components/Hello'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hello name="Lucas"></Hello>
      <ColorModeButton></ColorModeButton>
    </>
  )
}
