import Head from 'next/head'

import Hello from '../components/Hello'
import Header from '../components/Header'
import MeetMe from '../components/MeetMe'
import Employers from '../components/Employers'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Hello name="Lucas"></Hello>
      <MeetMe></MeetMe>
      <Employers></Employers>
      <Footer></Footer>
    </>
  )
}
